### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by epidrome** [ioniodi/scholardi#15]
Μερικά από παρακάτω δύσκολα ζητούμενα απαιτούν την δημιουργία νέων θεμάτων συζήτησης στο αποθετήριο του κώδικα έτσι ώστε να γίνουν περισσότερο εστιασμένα

Η προθεσμία τα εύκολα είναι το 1ο παραδοτέο και για τα δύσκολα το 2ο.

## Εύκολα

- [ ] BibTeX files are not correct #12  e.g., some publications do not belong to the respective scholar
https://ioniodi.github.io/scholardi/scholars0/choko/

- [ ] Add new layout for dynamic display of abstract (if any) for each publication in a list #14 , for example: http://pdf.epidro.me/

## Δύσκολα

- [ ] Instead of a separate pages, when a scholar has more than 10-20 publications add a dynamic display #13  e.g., google scholar

- [ ] search into titles (and abstracts if any) of publications #10
